#+HUGO_BASE_DIR: .
#+MACRO: uva @@hugo:{{<UVa2 number="$1" >}}@@


* Videos
:PROPERTIES:
:HUGO_SECTION: videos
:EXPORT_HUGO_SECTION: videos
:END:

** Line Sweep Convex Hull
:PROPERTIES:
:EXPORT_FILE_NAME: line-sweep-convex-hull
:END:

#+HTML: <video id="my-video" controls preload="auto" width="720" data-setup="playbackRates: [0.5,1,1.5,2]">
#+HTML:   <source type="video/mp4" src="/videos/LineSweepConvexHull.mp4"}></source>
#+HTML: </video>

** Line Sweep Closest Points
:PROPERTIES:
:EXPORT_FILE_NAME: line-sweep-closest-points
:END:

#+HTML: <video id="my-video" controls preload="auto" width="720" data-setup="playbackRates: [0.5,1,1.5,2]">
#+HTML:   <source type="video/mp4" src="/videos/LineSweepClosestPoints.mp4"}></source>
#+HTML: </video>

** Line Sweep Area of Union
:PROPERTIES:
:EXPORT_FILE_NAME: line-sweep-area-of-union
:END:

#+HTML: <video id="my-video" controls preload="auto" width="720" data-setup="playbackRates: [0.5,1,1.5,2]">
#+HTML:   <source type="video/mp4" src="/videos/LineSweepAreaOfUnion.mp4"}></source>
#+HTML: </video>

* Docs
:PROPERTIES:
:HUGO_SECTION: docs
:EXPORT_HUGO_SECTION: docs
:END:

** Why Take This Course?
:PROPERTIES:
:EXPORT_FILE_NAME: why-take-this-course
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 1 :date 2022-08-22 :publishdate 2022-07-01
:END:

Welcome to Competitive Programming!  In this class you will learn how to compete in programming contests such as ICPC,
Code Forces, and Hacker Rank.  *Is this class for you?  Read on to find out...*

*** What Are the Benefits of Competitive Programming?

Participating in coding contests has benefits!

  You will
  - build confidence in your coding skills,
  - increase your coding speed,
  - be ready to crush a coding interview,
  - and quite possibly make some friends!

*** But... I'm not very competitive, and besides, I'll never beat those top students!

That doesn't matter!  Whether you are just starting out or whether you are competing for a chance at the World Finals,
the only person you're really trying to beat is yourself.  The goal is to try hard, do a little bit better than last time,
or perhaps learn something that will help you next time.  You can do practice problems on your own, but there's nothing
like a contest to keep you honest.

*** Am I ready for this course?

The only prerequisite is that we assume you know how to program.  We don't even assume you're any good at it... this course
will help with that part.  But if you have programmed in Python, C, or C++ then you are ready for this course.

It does help if you've taken data structures and a theory course... but you can get started now and take those later as you
get stronger.

** Getting Started
:PROPERTIES:
:EXPORT_FILE_NAME: getting-started
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 2 :date 2022-08-22 :publishdate 2022-07-01
:END:

*** How Do I Get Started?

  - Join the CampusWire forum.  If you registered before class started, you should have gotten an invite.  If you registered late,
    or did not get the invite, you need to email the instructor.
  - It is recommended that you get these books:
    - [[https://cpbook.net][Competitive Programming 4]].  It is a two book set.
    - [[https://link.springer.com/book/10.1007/978-3-319-72547-5][Guide to Competitive Programming]].  As of this writing the PDF is free.
  - Register on [[https://codeforces.com][Code Forces]].  Your username *will be visible* to other students; you can create a "throwaway"
    account if you want just for this course.
    - Once you are registered, join [[https://codeforces.com/group/C1FCILxvRp/contests][the class group]].  This is where your problems
      will be hosted.
  - Also register on https://vjudge.net
    - THe class group is at https://vjudge.net/group/uiuc-cs491-sp23

*** How do I get good at this?

Practice.  A lot.  But do it efficiently...

  - Attend contests as much as you can.
    - [[https://codeforces.com][Code Forces]] has two hour long contests usually once or twice a week, for instance.
    - After the contest is over, read the commentary, both for the problems you solved, and the problems you attempted and could not solve.
    - Upsolve the ones you couldn't do.  (I don't know why they call it upsolving.)  This means that you go back to the computer, finish
      your solution, and submit it until you get it accepted.
  - Solve practice problems
    - This has a similar feel, but in this case it's okay get help.  If you are solving UVa problems you can use the UDebug and UHunt
      sites for extra hints / sample inputs.

** Syllabus
:PROPERTIES:
:EXPORT_FILE_NAME: syllabus
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 3 :date 2022-08-22 :publishdate 2022-07-01
:END:

*** Location and Times

  - Course Title: Introduction to Competitive Programming
  - Rubric: CS 491 CAP
  - CRN: 31584
  - Dates: January 18th, 2023 to May 4th 2023
  - Time: 14:00 &ndash; 14:50
  - Location: 2310 Everitt
  - Instructor: Mattox Beckman
  - Recommended Textbooks:
     - [[https://cpbook.org][Competitive Programming 4]]
     - [[https://link.springer.com/book/10.1007/978-3-319-72547-5][Guide to Competitive Programming]]
  - Prerequisites: ability to program is necessary; CS 225 strongly recommended.  We will use C++ for our content, but you are welcome to use
    a different language.
  - Office Hours: tba

*** Purpose

The purpose of this course is to prepare you to compete in ICPC-style competitive programming contests.  While this will help
you compete in the Illinois Programming League, Hacker Rank, Code Forces, or similar contests, learning this material has been shown
to help with programming assignments in other courses, and many students learn this material to become confident and skillful in coding
interviews.

*** Objectives and Outcomes

Upon successfully completing this course, you will have solved many programming problems.  You will have learned to select the correct
algorithm depending on the problem constraints and available time and memory resources.  You will have learned to implement your
solutions quickly and accurately, being given minimal guidance if your solution is incorrect.  You will have learned to work on your own
and in an ICPC style team of students using one computer.  And hopefully you will have a lot of fun doing so!

*** Class Structure

This is a flipped classroom.  You will be given a reading from the textbook, a short video to watch, and a sample problem or two to solve before class.
During class the instructor will ask for student comments about the problems and give commentary.   Afterward, there will be one or two more problems
for you to do during class.  Sometimes you will be asked to solve them individually, sometimes you will be placed in a team.  Once every two weeks we
will also release a problem set with a variety of problems to give you practice picking the correct algorithm to use.

*** Assignments and Grading

This course is a Credit/No Credit course.  To get credit, you must complete 70% of the class-related problems, attend at least 70% of
the class sessions (or have made other arrangements), and complete six of the given bi-weekly
problem sets.  You may also get problem set credit by competing in an ICPC tryout or other significant externally held contest.

We will also have an assignment where you prepare a Team Reference Document.  This assignment is not required, but highly recommended.

*** Students with Disabilities

To obtain disability-related academic adjustments and/or auxiliary aids,
students with disabilities must contact the course instructor as soon as
possible. To insure that disability-related concerns are properly
addressed from the beginning, students with disabilities who require
assistance to participate in this class should contact disability
resources and educational services
([[https://www.disability.illinois.edu/)][DRES]] and see the instructor
as soon as possible. If you need accommodations for any sort of
disability, please speak to me after class, or make an appointment to
see me, or see me during my office hours. DRES provides students with
academic accommodations, access, and support services. To contact DRES
you may visit 1207 S. Oak St., Champaign, call 333-4603 (v/tdd), or
e-mail a message to [[mailto:disability@uiuc.edu][disability@uiuc.edu]].

*** Emergency Response Recommendations

The university police have posted some [[http://police.illinois.edu/emergency/][emergency response recommendations]]. I
encourage you to review this website and the campus building
[[http://police.illinois.edu/emergency-preparedness/building-emergency-action-plans/][floor plans website]]
within the first 10 days of class.

Of course, since we're all online, your classroom is likely your living space.  Have you considered making
a fire safety plan with your family or roommates?

*** Family Educational Rights and Privacy Act (FERPA)


Any student who has suppressed their directory information pursuant to family
educational rights and privacy act (FERPA) should self-identify to the
instructor to ensure protection of the privacy of their attendance in this
course. see the [[http://registrar.illinois.edu/ferpa][FERPA]] site for more information.

*** Mental Health

Diminished mental health, including significant stress, mood changes, excessive
worry, substance/alcohol abuse, or problems with eating and/or sleeping can
interfere with optimal academic performance, social development, and emotional
wellbeing. The University of Illinois offers a variety of confidential services
including individual and group counseling, crisis intervention, psychiatric
services, and specialized screenings at no additional cost. If you or someone
you know experiences any of the above mental health concerns, it is strongly
encouraged to contact or visit any of the University's resources provided below.
Getting help is a smart and courageous thing to do -- for yourself and for those
who care about you.

Counseling Center: 217-333-3704, 610 East John Street Champaign, IL 61820

McKinley Health Center:217-333-2700, 1109 South Lincoln Avenue, Urbana, Illinois 61801

** Schedule
:PROPERTIES:
:EXPORT_FILE_NAME: schedule
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 4
:EXPORT_DATE: 2023-01-18
:END:

| Week | Date        | Lecture Topic / Objectives       |
|------+-------------+----------------------------------|
|    1 | January 18  | [[*Course Introduction]]         |
|      | January 20  | [[*IO]]                          |
|------+-------------+----------------------------------|
|    2 | January 23  | [[*Standard Template Library]]   |
|      | January 25  | [[*Complete Search]]             |
|      | January 27  | [[*Divide and Conquer]]          |
|------+-------------+----------------------------------|
|    3 | January 30  | [[*Greedy Algorithms]]           |
|      | February 1  | [[*Dynamic Programming]]         |
|------+-------------+----------------------------------|
|    5 | February 13 | [[*Graph Representations]]       |
|------+-------------+----------------------------------|
|    6 | February 20 | [[*Single Source Shortest Path]] |
|      | February 22 | [[*All Points Shortest Path]]    |
|      | February 24 | [[*Traversals 2]]                |
|------+-------------+----------------------------------|
|    7 | February 27 | [[*Network Flow]]                |
|      | March 1     | [[*Prime Numbers]]               |
|------+-------------+----------------------------------|
|    8 | March 6     | [[*Combinatorics]]               |
|      | March 8     | [[*GCD]]                         |
|    9 | March 20    | [[*Bit Manipulation]]            |
|      | March 22    | [[*Traveling Sales Person]]      |

* Lectures
:PROPERTIES:
:HUGO_SECTION: lectures
:EXPORT_HUGO_SECTION: lectures
:END:

** Course Introduction
:PROPERTIES:
:ID:       d6691455-f4dc-44ec-b6ae-2b169766e1af
:EXPORT_FILE_NAME: course-introduction
:EXPORT_DATE: 2023-01-18
:END:

Welcome to Competitive Programming!  Today we will talk about the benefits of competitive programming, the course structure, and the tools we will
use in the course.

*** Slides
- [[/slides/course-introduction.pdf][Course Introduction Slides]]

*** Judge Links
  - Register on [[https://codeforces.com][Code Forces]].  Your username *will be visible* to other students; you can create a "throwaway"
    account if you want just for this course.
    - Once you are registered, join [[https://codeforces.com/group/C1FCILxvRp/contests][the Class Group]].  This is where your problems
      will be hosted.
  - Similarly, register on [[https://vjudge.net][VJudge.net]] and for the [[https://vjudge.net/group/uiuc-cs491-sp23][Class Group]].

** IO
:PROPERTIES:
:ID:       dd79861f-468e-4462-8b45-50c146180aeb
:EXPORT_FILE_NAME: io
:EXPORT_DATE: 2023-01-20
:END:

The first thing your program needs to do is read in the test data and convert it to an internal structure.
There are several patterns that test cases follow, and you will need to handle each one a bit differently.
It all comes down to knowing how much data you are going to get.  There are three primary ways you find this out:

- An explicit count
- A special marker (like a terminating zero)
- Simply getting an end-of-file

We will also talk about formatting options.

We don't have a video for this lecture, but here are some slides with all the content.

*** Slides
- [[/slides/io.pdf][IO Slides]]

** Standard Template Library
:PROPERTIES:
:EXPORT_FILE_NAME: standard-template-library
:EXPORT_DATE: 2023-01-23
:ID:       fe376ef5-8f74-4277-a1d7-850a09fe14a6
:END:

Today we will discuss the standard template library for C++.  You don't have to use this for your own
programming, but we will use it in our examples so you should know how it all works.

*** Slides
- [[/slides/standard-template-library.pdf][STL Slides]]


** Complete Search
:PROPERTIES:
:EXPORT_FILE_NAME: complete-search
:EXPORT_DATE: 2023-01-25
:ID:       846b343c-763c-45cc-a5a0-ff515285cb06
:END:

Also knowns as "brute force"; this paradigm happens when there's nothing to do but check all the possible solutions.

BUT!!!  That doesn't mean that you can't be clever how you do it.

*** Slides
- [[/slides/complete-search.pdf][Complete Search Slides]]


** Divide and Conquer
:PROPERTIES:
:EXPORT_FILE_NAME: divide-and-conquer
:EXPORT_DATE: 2023-01-27
:ID:       99caeb59-31db-4e9d-a2cd-7c905eddedc0
:END:

Divide and conquer allows you to split a problem up, usually eliminating half of the search space.

*** Slides
- [[/slides/divide-and-conquer.pdf][Divide and Conquer Slides]]

** Greedy Algorithms
:PROPERTIES:
:EXPORT_FILE_NAME: greedy-algorithms
:EXPORT_DATE: 2023-01-30
:ID:       536a6476-b1c4-4dd7-b720-44a06977ecf4
:END:

*** Slides
- [[/slides/greedy-algorithms.pdf][Greedy Algorithms Slides]]

** Dynamic Programming
:PROPERTIES:
:EXPORT_FILE_NAME: dynamic-programming
:EXPORT_DATE: 2023-02-01
:ID:       61027489-7f78-493b-b559-4422cde4bc43
:END:

*** Slides
- [[/slides/dynamic-programming.pdf][Dynamic Programming Slides]]

** Graph Representations
:PROPERTIES:
:EXPORT_FILE_NAME: graph-representations
:EXPORT_DATE: 2023-02-13
:ID:       ca2dbeb0-083d-4f98-95ad-c429bf32bae9
:END:

*** Slides
- [[/slides/graph-representation.pdf][Graph Representation Slides]]


** Single Source Shortest Path
:PROPERTIES:
:EXPORT_FILE_NAME: single-source-shortest-path
:EXPORT_DATE: 2023-02-20
:ID:       4e09691a-8f1a-4fd3-8b5c-f75251bcb105
:END:

*** Slides

- [[/slides/bfs-shortest-path.pdf][BFS Shortest Path]]
- [[/slides/dijkstra-shortest-path.pdf][Dijkstra's Shortest Path Algorithm]]
- [[/slides/bellman-ford-and-spfa.pdf][Bellman Ford and SPFA]]


** All Points Shortest Path
:PROPERTIES:
:EXPORT_FILE_NAME: single-source-shortest-path
:EXPORT_DATE: 2023-02-20
:ID:       68db99bd-53c6-4425-aa45-c37d63573504
:END:

*** Slides

- [[/slides/floyd-warshall.pdf][Floyd Warshall]]

** Traversals 2
:PROPERTIES:
:EXPORT_FILE_NAME: traversals-2
:EXPORT_DATE: 2023-02-24
:ID:       5c13742e-38e0-4436-8d7b-426af1f28ee5
:END:

*** Slides

- [[/slides/traversals-2.pdf][Traversals 2]]


** Network Flow
:PROPERTIES:
:EXPORT_FILE_NAME: network-flow
:EXPORT_DATE: 2023-02-27
:ID:       0422089d-5d4e-4d32-bed1-d0a4dfb47870
:END:

The Edmonds-Karp algorithm is a popular and efficient algorithm used to solve the max-flow problem in network flow
theory. This algorithm is an extension of the Ford-Fulkerson algorithm, which is a simple algorithm for finding the
maximum flow in a network. The Edmonds-Karp algorithm uses a breadth-first search approach to find the shortest
augmenting path in the residual graph, making it faster and more efficient than the original Ford-Fulkerson algorithm.

*** Slides

- [[/slides/edmonds-karp.pdf][Edmonds Karp]]

** Prime Numbers
:PROPERTIES:
:EXPORT_FILE_NAME: prime-numbers
:EXPORT_DATE: 2023-03-01
:ID:       d621ddd6-0b6d-4175-b474-314799ed46ae
:END:

Prime numbers are a familiar feature in mathematics, and often come up in competitive programming.  In this lecture
we will derive the Sieve of Erastosthenes, show how to factor large numbers, and discuss the practical limits to the
number of prime numbers we can generate during a contest.

*** Slides

- [[/slides/prime-numbers.pdf][Prime Numbers]]

** Combinatorics
:PROPERTIES:
:EXPORT_FILE_NAME: combinatorics
:EXPORT_DATE: 2023-03-06
:ID:       d9bf37b1-8c13-4984-8448-adbf6f692b48
:END:

Combinatorics is the branch of mathematics that deals with counting and arranging objects.  We will cover some of the
fundamental concepts in combinatorics, including binomial coefficients, permutations, and derangements.

Binomial coefficients, also known as binomials, are a tool for counting the number of ways that a given set of objects
can be arranged or selected. We will explain how to calculate binomial coefficients  to model different scenarios such
as flipping coins or selecting items from a set.

A permutation is a reordering of a set of items.  We will explain how to count the number of permutations and how to
generate all the permutations of a given set. Derangements are permutations where no element appears in its original
position.  We will examine how to calculate the number of derangements for a set and discuss its applications.

*** Slides

- [[/slides/combinatorics.pdf][Combinatorics]]


** GCD
:PROPERTIES:
:EXPORT_FILE_NAME: GCD
:EXPORT_DATE: 2023-03-08
:ID:       f118cc9f-89b0-4a60-92e7-ed16708011fb
:END:

GCD, or Greatest Common Divisor, is a mathematical concept that refers to the largest positive integer that divides two or more numbers without leaving a remainder.

In class we will derive Euclid's algorithm, an efficient way of computing GCD, as well as explore some of the properties of GCD you will want to know when solving
competitve programming problems.

*** Materials

- [[/handouts/gcd.pdf][GCD Handout]]

** Inclusion/Exclusion
:PROPERTIES:
:EXPORT_FILE_NAME: inclusion-exclusion
:EXPORT_DATE: 2023-03-08
:ID:       f118cc9f-89b0-4a60-92e7-ed16708011fb
:END:

The principle of inclusion/exclusion is a counting technique used to calculate the size of a union of sets. It states that:

$|A \cup B \cup C| = |A| + |B| + |C| - |A \cap B| - |B \cap C| - |A \cap C| + |A \cap B \cap C|$

where $A$, $B$, and $C$ are any finite sets.

In other words, to find the size of the union of three sets $A$, $B$, and $C$, you first add the sizes of each set
individually, then subtract the sizes of the overlaps $(A \cap B, B \cap C$, and $A \cap C$), and finally add the size of the
triple overlap $(A \cap B \cap C)$.

This principle can be extended to any number of sets, and is a useful tool in combinatorics, probability theory, and
other areas of mathematics.

*** Materials

- [[/slides/inclusion-exclusion.pdf][Inclusion-Exclusion Slides]]

** Bit Manipulation
:PROPERTIES:
:EXPORT_FILE_NAME: bit-manipulation
:EXPORT_DATE: 2023-03-20
:ID:       d7d4e811-1f15-42ca-b44c-fd51153aa8e1
:END:

*** Materials

- [[/slides/bit-manipulations.pdf][Slides]]

** Traveling Sales Person
:PROPERTIES:
:EXPORT_FILE_NAME: tsp
:EXPORT_DATE: 2023-03-22
:ID:       d7d4e811-1f15-42ca-b44c-fd51153aa8e1
:END:

The Traveling Salesperson Problem (TSP) is a well-known problem in computer science and operations research that asks
for the shortest possible route that visits every city exactly once and returns to the starting city.  TSP has many
practical applications, including in logistics, transportation planning, and circuit board design.

*** Materials

- [[/handouts/tsp-handout.pdf][Handout]]
- [[/slides/tsp-slides.pdf][Slides]]

** Fast Exponentiation
:PROPERTIES:
:EXPORT_FILE_NAME: fast-exponentiation
:EXPORT_DATE: 2023-03-24
:ID:       71052961-1628-496c-b36d-7e223977c62d
:END:

Exponents are fun, but using bit techniques we covered last time we can compute them significantly faster than the standard technique.
This generalizes to other forms as well, such as computing Fibonacci numbers is sub-linear time.

*** Materials

- [[/slides/fast-exponentiation.pdf][Slides]]

** Points, Lines, and Vectors
:PROPERTIES:
:EXPORT_FILE_NAME: points-lines-vectors
:EXPORT_DATE: 2023-03-27
:ID:       bd6ab2e0-c715-428f-a055-5e8cc58708d2
:END:

*** Materials

- [[/slides/points-lines-vectors-slides.pdf][Slides]]

** Line Sweep
:PROPERTIES:
:EXPORT_FILE_NAME: line-sweep
:EXPORT_DATE: 2023-04-05
:END:

*** Materials

- [[*Line Sweep Convex Hull]] Video
- [[*Line Sweep Closest Points]] Video
- [[*Line Sweep Area of Union]] Video



* End :noexport:
;; Local Variables:
;; eval: (org-link-set-parameters "class" :export #'my-org-export-class-link)
;; End:
